"""Fix runner and interactive remediation menu.

INVARIANT: Every string passed to _run_fix_cmd() must be a code literal authored
in checks/*.py, never built from untrusted/user/env-derived input.  shell=True is
intentional for POSIX (allows pipes and redirects in fix_cmds); Windows uses an
explicit powershell argv list instead.  Any fix_cmd that interpolates a filesystem
path MUST use shlex.quote() (POSIX) or _ps_quote() (PowerShell).
"""

import argparse
import errno
import json
import os
import shlex
import shutil
import subprocess
import sys

from ._core import _OS, _ps, _NO_WINDOW
from ._report import _load_report

def _run_fix_cmd(cmd):
    """Run a single shell fix command. Returns (returncode, combined_output)."""
    try:
        if _OS == "Windows":
            no_window = getattr(subprocess, "CREATE_NO_WINDOW", 0)
            full_cmd = f"$ErrorActionPreference = 'Stop'; {cmd}"
            result = subprocess.run(
                ["powershell", "-NonInteractive", "-NoProfile", "-Command", full_cmd],
                capture_output=True, text=True, errors="replace", timeout=120,
                creationflags=no_window,
            )
            return result.returncode, (result.stdout + result.stderr).strip()
        result = subprocess.run(
            cmd, shell=True, text=True, errors="replace",
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            timeout=60,
        )
        return result.returncode, result.stdout.strip()
    except subprocess.TimeoutExpired:
        return 1, "timed out"
    except OSError as e:
        if e.errno == errno.EDQUOT:
            return 1, "disk quota exceeded — free up disk space before applying fixes"
        if e.errno == errno.ENOSPC:
            return 1, "no space left on device — free up disk space before applying fixes"
        return 1, str(e)
    except Exception as e:
        return 1, str(e)


def _check_disk_space(min_mb: int = 50):
    """Return a warning string if disk space is critically low, else None."""
    try:
        usage = shutil.disk_usage("/")
        free_mb = usage.free / (1024 * 1024)
        if free_mb < min_mb:
            return (f"Only {free_mb:.0f} MB free on disk — fixes that write to disk "
                    f"will fail. Free up space before continuing.")
    except OSError:
        pass
    return None


def _collect_fixable(report_data):
    """Return flat list of (check, label, fix_cmds) for all fixable findings."""
    items = []
    for check in report_data.get("checks", []):
        for f in check.get("findings", []):
            cmds = f.get("fix_cmds", [])
            if cmds:
                items.append({
                    "check": check["check"],
                    "label": f["label"],
                    "severity": f["severity"],
                    "fix_cmds": cmds,
                })
    return items


def _print_remediation_menu(items):
    width = 66
    print("=" * width)
    print("  FIXABLE FINDINGS")
    print("=" * width)
    if not items:
        print("  No findings with automated fixes in this report.")
        print("=" * width)
        return
    for i, item in enumerate(items, 1):
        sev = item["severity"]
        print(f"\n  [{i}] [{sev}]  {item['check']} / {item['label']}")
        for cmd in item["fix_cmds"]:
            print(f"       $ {cmd}")
    print()
    print("-" * width)


def _remediate_main(argv):
    parser = argparse.ArgumentParser(
        prog="gullwing remediate",
        description="Apply automated fixes from a saved scan report.\n\n"
                    "WARNING: Only run this on reports generated by this tool on "
                    "systems you own. Fix commands are executed with your current "
                    "privileges — use sudo if root access is required.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("report", help="JSON report file produced by --output.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show fix commands without executing them.")
    parser.add_argument("--all", dest="fix_all", action="store_true",
                        help="Apply all available fixes.")
    parser.add_argument("--item", metavar="N", type=int, action="append",
                        dest="items", default=[],
                        help="Apply fix for finding number N (repeatable).")
    parser.add_argument("--yes", action="store_true",
                        help="Skip per-fix confirmation prompts.")
    args = parser.parse_args(argv)

    data, err = _load_report(args.report)
    if err:
        print(f"[!] {err}", file=sys.stderr)
        sys.exit(1)

    fixable = _collect_fixable(data)
    _print_remediation_menu(fixable)

    if not fixable or args.dry_run:
        return

    # Determine which items to fix
    if args.fix_all:
        selected = list(range(len(fixable)))
    elif args.items:
        selected = []
        for n in args.items:
            if 1 <= n <= len(fixable):
                selected.append(n - 1)
            else:
                print(f"[!] Item {n} out of range (1–{len(fixable)}).", file=sys.stderr)
                sys.exit(1)
    else:
        # Interactive menu
        try:
            raw = input("Enter item numbers to fix (e.g. 1,3), 'all', or 'q' to quit: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return
        if raw.lower() in ("q", "quit", ""):
            return
        if raw.lower() == "all":
            selected = list(range(len(fixable)))
        else:
            selected = []
            for part in raw.replace(" ", "").split(","):
                try:
                    n = int(part)
                except ValueError:
                    print(f"[!] Invalid input: {part!r}", file=sys.stderr)
                    sys.exit(1)
                if not (1 <= n <= len(fixable)):
                    print(f"[!] Item {n} out of range (1–{len(fixable)}).", file=sys.stderr)
                    sys.exit(1)
                selected.append(n - 1)

    # Execute
    failed = 0
    for idx in selected:
        item = fixable[idx]
        print(f"\n── Fixing [{item['severity']}] {item['label']} ──")
        for cmd in item["fix_cmds"]:
            print(f"  $ {cmd}")
            if not args.yes:
                try:
                    confirm = input("  Run this command? [y/N] ").strip().lower()
                except (EOFError, KeyboardInterrupt):
                    print()
                    return
                if confirm not in ("y", "yes"):
                    print("  Skipped.")
                    continue
            rc, out = _run_fix_cmd(cmd)
            if rc == 0:
                print(f"  ✓ OK" + (f": {out}" if out else ""))
            else:
                print(f"  ✗ FAILED (exit {rc})" + (f": {out}" if out else ""))
                failed += 1

    if failed:
        print(f"\n[!] {failed} command(s) failed.", file=sys.stderr)
        sys.exit(1)
    else:
        print("\n[+] All selected fixes applied.")


# ── Email notification ────────────────────────────────────────────────────────

